# Generated by Django 4.2 on 2024-09-16 16:18

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("street_address", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("postal_code", models.CharField(max_length=20)),
                ("country", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Package",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                (
                    "status",
                    models.IntegerField(choices=[(0, "Inactive"), (1, "Active")], default=1, verbose_name="status"),
                ),
                (
                    "activate_date",
                    models.DateTimeField(blank=True, help_text="keep empty for an immediate activation", null=True),
                ),
                (
                    "deactivate_date",
                    models.DateTimeField(blank=True, help_text="keep empty for indefinite activation", null=True),
                ),
                (
                    "tracking_number",
                    django_extensions.db.fields.RandomCharField(
                        blank=True,
                        editable=False,
                        help_text="Autogenerated random code to track a package.",
                        length=8,
                        unique=True,
                    ),
                ),
                (
                    "destination_address",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="destination_packages",
                        to="core.address",
                    ),
                ),
                (
                    "origin_address",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="origin_packages",
                        to="core.address",
                    ),
                ),
            ],
            options={
                "ordering": ["created"],
            },
        ),
        migrations.CreateModel(
            name="TrackingHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("location", models.CharField(max_length=100)),
                ("timestamp", django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="tracking_history", to="core.package"
                    ),
                ),
            ],
            options={
                "ordering": ["package", "-timestamp"],
            },
        ),
    ]
