from django.db import models
from django_extensions.db.fields import CreationDateTimeField, RandomCharField
from django_extensions.db.models import ActivatorModel, TimeStampedModel


class Address(models.Model):
    street_address = models.CharField(max_length=255)
    city = models.CharField(max_length=100)
    state = models.CharField(max_length=100)
    postal_code = models.CharField(max_length=20)
    country = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.street_address}. {self.postal_code} - {self.city}"


class Package(ActivatorModel, TimeStampedModel, models.Model):
    tracking_number = RandomCharField(length=8, unique=True, help_text="Autogenerated random code to track a package.")
    origin_address = models.ForeignKey(Address, on_delete=models.SET_NULL, null=True, related_name="origin_packages")
    destination_address = models.ForeignKey(
        Address, on_delete=models.SET_NULL, null=True, related_name="destination_packages"
    )

    class Meta:
        ordering = ["created"]

    def __str__(self):
        return f"{self.tracking_number} ({self.status})"


class TrackingHistory(models.Model):
    package = models.ForeignKey(Package, on_delete=models.CASCADE, related_name="tracking_history")
    location = models.CharField(max_length=100)
    timestamp = CreationDateTimeField()

    class Meta:
        ordering = ["package", "-timestamp"]

    def __str__(self):
        return f"{self.package.tracking_number} - {self.location} at {self.timestamp}"
